tables:
  users:
    CREATE TABLE users (
      handle TEXT NOT NULL PRIMARY KEY,
      name TEXT NOT NULL,
      auth INTEGER NOT NULL UNIQUE,
      registerDate TEXT NOT NULL,
      lastLogin TEXT NOT NULL
    );
  follows:
    CREATE TABLE follows (
      follower TEXT NOT NULL,
      followed TEXT NOT NULL,
      since TEXT NOT NULL,
      FOREIGN KEY(follower) REFERENCES users(handle),
      FOREIGN KEY(followed) REFERENCES users(handle),
      PRIMARY KEY (follower, followed)
    );
  bans:
    CREATE TABLE bans (
      banisher TEXT NOT NULL,
      banished TEXT NOT NULL,
      since TEXT NOT NULL,
      FOREIGN KEY(banisher) REFERENCES users(handle),
      FOREIGN KEY(banished) REFERENCES users(handle),
      PRIMARY KEY (banisher, banished)
    );
  photos:
    CREATE TABLE photos (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      author TEXT NOT NULL,
      title TEXT NOT NULL,
      uploadDate TEXT NOT NULL,
      file BLOB NOT NULL,
      FOREIGN KEY(author) REFERENCES users(handle)
    );
  likes:
    CREATE TABLE likes (
      photoId INTEGER NOT NULL,
      liker TEXT NOT NULL,
      since TEXT NOT NULL,
      FOREIGN KEY(liker) REFERENCES users(handle),
      FOREIGN KEY(photoId) REFERENCES photos(id),
      PRIMARY KEY (photoId, liker)
    );
  comments:
    CREATE TABLE comments (
      photoId INTEGER NOT NULL,
      id INTEGER NOT NULL,
      author TEXT NOT NULL,
      content TEXT NOT NULL,
      since TEXT NOT NULL,
      FOREIGN KEY(author) REFERENCES users(handle),
      FOREIGN KEY(photoId) REFERENCES photos(id),
      PRIMARY KEY (photoId, id)
    );
triggers:
  commentsIncr: # To increment the comment id and add a date
    CREATE TRIGGER commentsIncr
      BEFORE INSERT ON comments
    BEGIN
      NEW.id = SELECT photos.commentsI
        FROM photos
        WHERE photos.id = NEW.photoId;
      UPDATE photos
        SET photos.commentsI = NEW.id + 1
        WHERE photos.id = NEW.photoId;
      NEW.since = strftime('%Y-%m-%dT%H:%M', 'now')
    END;
  likesDate:
    CREATE TRIGGER likesDate
      BEFORE INSERT ON likes
    BEGIN
      NEW.since = strftime('%Y-%m-%dT%H:%M', 'now')
    END;
  photosDate:
    CREATE TRIGGER photosDate
      BEFORE INSERT ON photos
    BEGIN
      NEW.uploadDate = strftime('%Y-%m-%dT%H:%M', 'now')
    END;
  bansDate:
    CREATE TRIGGER bansDate
      BEFORE INSERT ON bans
    BEGIN
      NEW.since = strftime('%Y-%m-%dT%H:%M', 'now')
    END;
  followsDate:
    CREATE TRIGGER followsDate
      BEFORE INSERT ON follows
    BEGIN
      NEW.since = strftime('%Y-%m-%dT%H:%M', 'now')
    END;
  usersRegDate:
    CREATE TRIGGER usersRegDate
      BEFORE INSERT ON users
    BEGIN
      NEW.registerDate = strftime('%Y-%m-%dT%H:%M', 'now')
    END;