openapi: '3.0.2'
info:
  title: WASAPhoto
  description: |-
    This is Davide Marincione's API for his WASAPhoto implementation
  version: '1.0.0'
servers:
  - url: http://localhost/
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    InternalServerError:
      description: |-
        The server encountered an internal error.
        Welp...
  schemas:
    userId:
      title: User identifier
      description: A user's id
      type: integer
      example: 90635441
      format: int64
    userName:
      title: User name
      description: regex definition of an acceptable username
      type: string
      example: Maria
      pattern: '^.*?$'
      minLength: 4
      maxLength: 32
    photoRaw:
      title: Photo representation
      description: How a photo is represented in this application
      type: string
      format: binary
      maxLength: 52428800 # 50 MiB
      # TODO:
      #   1- add maximum length (?)
      #   2- IF above, add ability to combine multiple photos
      #     to get arbitrarily sized images
    photoTitle:
      title: Post title
      example: A curious title
      type: string
      minLength: 4
      maxLength: 64
    photoId:
      title: Photo identifier
      example: 123456
      type: integer
      format: int64
    photo:
      title: Photo post
      description: A post of a user's photo
      type: object
      properties:
        id:
          $ref: "#/components/schemas/photoId"
        date:
          type: string
          format: date-time
        photo:
          $ref: "#/components/schemas/photoRaw"
        title:
          $ref: "#/components/schemas/photoTitle"
    comment:
      title: Comment
      description: A user's comment under a photo
      type: object
      properties:
        text:
          type: string
          minLength: 1
          maxLength: 256
        author:
          $ref: "#/components/schemas/userName"
        date:
          type: string
          format: date-time
paths:
  /users:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      parameters:
        - in: query
          name: username
          schema:
            $ref: "#/components/schemas/userName"
          required: true
      responses:
        '200':
          description: User log-in action successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userId"
        '201':
          description: User log-in (registration) action successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userId"
        '400':
          description: Unacceptable username
        '500':
           $ref: '#/components/responses/InternalServerError'
  /users/{userName}:
    parameters:
      - in: path
        name: userName
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: header
        name: userId
        schema:
          $ref: "#/components/schemas/userId"
        required: false
    put:
      security:
      - bearerAuth: []
      tags: ["user"]
      summary: Modify username
      description: |-
        Modifies the user name
      operationId: setMyUserName
      parameters:
        - in: query
          name: newUserName
          schema:
            $ref: "#/components/schemas/userName"
          required: true
      responses:
        '200':
          description: Username change successfull
          # Maybe should return userRepr
        '400':
          description: Unacceptable username
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
        '500':
           $ref: '#/components/responses/InternalServerError'
    get:
      tags: ["user"]
      summary: Get user profile
      description: |-
        Requests a user's profile
      operationId: getUserProfile
      responses:
        '200':
          description: Returning user's profile
          # TODO: return the user and all of his photos
        '404':
          description: User not found
        '500':
           $ref: '#/components/responses/InternalServerError'
  # I am not at all happy with the current state of the followed and banned users,
  # put/delete operations should create and delete resources, but in this case I 
  # am forced to make them modify the resource... unfortunately though I have to
  # provide the operationId's, therefore this.
  /users/{userName}/is-following:
    parameters:
      - in: path
        name: userName
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: query
        name: otherUser
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: header
        name: userId
        schema:
          $ref: "#/components/schemas/userId"
        required: false
    put:
      security:
      - bearerAuth: []
      tags: ["follow"]
      summary: Follow user
      description: |-
        Follows user if it is not followed (cannot follow self)
      operationId: followUser
      responses:
        '200':
          description: Successful addition
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
        '409':
          description: Cannot follow self
        '410':
          description: Other user not found
        '500':
           $ref: '#/components/responses/InternalServerError'
    delete:
      security:
      - bearerAuth: []
      tags: ["follow"]
      summary: Un-follow user
      description: |-
        Un-follows user if it is followed
      operationId: unfollowUser
      responses:
        '200':
          description: Successful removal
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
        '500':
           $ref: '#/components/responses/InternalServerError'
  /users/{userName}/is-banning:
    parameters:
      - in: path
        name: userName
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: query
        name: otherUser
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: header
        name: userId
        schema:
          $ref: "#/components/schemas/userId"
        required: false
    put:
      security:
      - bearerAuth: []      
      tags: ["ban"]
      summary: Ban user
      description: |-
        Bans user if it is not yet banned (cannot ban self)
      operationId: banUser
      responses:
        '200':
          description: Successful addition
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
        '409':
          description: Cannot ban self
        '410':
          description: Other user not found
        '500':
           $ref: '#/components/responses/InternalServerError'
    delete:
      security:
      - bearerAuth: []  
      tags: ["ban"]
      summary: Un-ban user
      description: |-
        Un-bans user if it is banned
      operationId: unbanUser
      responses:
        '200':
          description: Successful removal
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
        '500':
           $ref: '#/components/responses/InternalServerError'
  /users/{userName}/stream:
    parameters:
      - in: path
        name: userName
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: header
        name: userId
        schema:
          $ref: "#/components/schemas/userId"
        required: false
    get:
      security:
      - bearerAuth: []  
      tags: ["stream"]
      summary: Receive stream
      description: |-
        Receive the user's stream filled with info from the people they follow
      operationId: getMyStream
      responses:
        '200':
          description: Here's your stream!
          # TODO: describe stream
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
        '500':
           $ref: '#/components/responses/InternalServerError'
  /users/{userName}/photos:
    parameters:
      - in: path
        name: userName
        schema:
          $ref: "#/components/schemas/userName"
        required: true 
      - in: header
        name: userId
        schema:
          $ref: "#/components/schemas/userId"
        required: false
    post:
      security:
      - bearerAuth: []  
      tags: ["post"]
      summary: Post a photo
      description: |-
        Add a post to the user's page
      operationId: uploadPhoto
      parameters:
        - in: header
          name: photo
          schema:
            type: object
            properties:
              title:
                $ref: "#/components/schemas/photoTitle"
              photo:
                $ref: "#/components/schemas/photoRaw"
          required: true
      responses:
        '201':
          description: Successful photo post
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/photoId"
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
        '413':
          description: Photo is too big!
        '500':
           $ref: '#/components/responses/InternalServerError'
  /users/{userName}/photos/{photoId}:
    parameters:
      - in: path
        name: userName
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: path
        name: photoId
        schema:
          $ref: "#/components/schemas/photoId"
        required: true
      - in: header
        name: userId
        schema:
          $ref: "#/components/schemas/userId"
        required: false
    delete:
      security:
      - bearerAuth: []
      tags: ["photo"]
      summary: Delete photo
      description: |-
        Delete a photo and all of its relative stuff (comments, likes, etc.)
      operationId: deletePhoto
      responses:
        '200':
          description: Photo removal successful
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User or photo not found
        '500':
           $ref: '#/components/responses/InternalServerError'
  /users/{userName}/photos/{photoId}/user-likes:
    parameters:
      - in: path
        name: userName
        schema:
          $ref: "#/components/schemas/userName"
        required: true
      - in: path
        name: photoId
        schema:
          $ref: "#/components/schemas/photoId"
        required: true
      - in: query
        name: self
        schema:
          $ref: "#/components/schemas/userName"
        required: false
      - in: header
        name: userId
        schema:
          $ref: "#/components/schemas/userId"
        required: false
    put:
      security:
      - bearerAuth: []      
      tags: ["like"]
      summary: Like photo
      description: |-
        Put a like on a photo (not on yours of course)
      operationId: likePhoto
      responses:
        '200':
          description: Successful like
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Recipient or photo not found
        '409':
          description: Cannot like self
        '410':
          description: Self not found
        '500':
           $ref: '#/components/responses/InternalServerError'
    delete:
      security:
      - bearerAuth: []  
      tags: ["like"]
      summary: Un-like photo
      description: |-
        Remove like from a photo
      operationId: unlikePhoto
      responses:
        '200':
          description: Successful removal
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Recipient or photo not found
        # TODO: decide if to keep 410
        '410':
          description: Self not found
        '500':
           $ref: '#/components/responses/InternalServerError'